name: Eleventy Build

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2


        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: '14'
        - run: npm install

        - name: Build static site
          run: npx @11ty/eleventy

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            # deploy_key: ${{ secrets.DEPLOY_KEY }} - expects ssh rather than deploy key
            github_token: ${{ secrets.GITHUB_TOKEN }}
            # external_repository: username/external-repository # Defaults to this repo
            publish_branch: gh-pages # default: gh-pages
            publish_dir: ./_site # default is public
            force_orphan: true # do not maintain history on gh-pages branch
